spring.application.name=clubconnect-backend

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG



# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA and Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

aws.region=us-east-1
aws.cognito.userPoolId=us-east-1_jpgVw25qp
aws.cognito.clientId=26qra88rinc083rehnm85d073m

# Cognito Configuration
spring.security.oauth2.client.registration.cognito.client-id=26qra88rinc083rehnm85d073m
spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_jpgVw25qp
spring.security.oauth2.client.registration.cognito.scope=openid,profile,email
spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.cognito.redirect-uri=http://localhost:8080/login/oauth2/code/cognito
